---
version: "3.9"

services:
  mysql:
    image: mariadb:latest
    restart: always
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
